spring:
  application:
    name: chat-manager-notification-service
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:8888

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
